### PR TITLE
add generic jenkinsfile

### PR DESCRIPTION
**Pull request by serhanwbahar**
I created a generic Jenkinsfile that takes parameters for each website.

### CODE REVIEW

**Comment by jakubgs** [comment]
I guess this is obsolete now?

**Comment by serhanwbahar** [comment]
> I guess this is obsolete now?

Do you mean absolute or obsolete?

**Comment by jakubgs** [comment]
I wrote "obsolete" so I mean "obsolete".

**Comment by serhanwbahar** [comment]
Hmm, then I don't get it. Why should it be obsolete?

**Comment by jakubgs** [comment]
Because we JUST discussed that it doesn't make sense to track changes in `logos-site-builder` since they are so rare they are not worth optimizing the build process for? And instead we should be starting the build from each site repo so that we track changes there automatically?

**Comment by serhanwbahar** [comment]
> Because we JUST discussed that it doesn't make sense to track changes in `logos-site-builder` since they are so rare they are not worth optimizing the build process for? And instead we should be starting the build from each site repo so that we track changes there automatically?

Oh right. Sorry about my misunderstanding the word. I should check the word's meaning before writing here. It is just my perfect English. 👎 (boo to me)

Yes, we should discard it since I'll create Jenkinsfile per each website repo.

**Pull request closed without merging**
